controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_test_index:
    path: /index
    controller: App\Controller\TestController::index
